import './globals.css'
import type { Metadata } from 'next'
import { Roboto_Condensed} from 'next/font/google'
import Header from "./common/header/header";




const roboto = Roboto_Condensed({weight: ["700", "400"], subsets: ['latin']} )
export const metadata: Metadata = {
  title: 'Amderrie',
  description: 'Generated by Knara',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
      <Header/>
      <div >
          {children}
      </div>
      </body>
    </html>
  )
}
